# -*- coding: utf-8 -*-
"""composition_value.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v6Ukw38NWHjBeTW6tT-jQjQPm5eJ5eym
"""

"""
composition_value.py

For each asteroid in dataset_cleaned.csv, computes:
  - Estimated bulk mass (kg)
  - Inferred composition class (C, S, M) and how it was determined
  - Expected useful mass E[M_useful] (kg)
  - Standard deviation sigma_M (kg) — uncertainty term in objective
  - Expected value ($USD) based on material composition

Classification logic (in priority order)
-----------------------------------------
1. spec_B (Bus-DeMeo, DeMeo et al. 2009) if available
   - C-complex → C-type
   - S-complex → S-type
   - X-complex → resolved by albedo using Tholen (1984) thresholds
     per Clark et al. (2004): albedo > 0.30 → E (treat as S),
     0.10-0.30 → M, < 0.10 → P (treat as C)
   - If albedo unavailable for X-complex → excluded (no estimate)
2. spec_T (Tholen 1984) if spec_B is null
   - M, E, P types resolved directly (Tholen defined by albedo)
3. albedo alone if both spectral types null
   - Tholen (1984) thresholds: > 0.30 → S, 0.10-0.30 → M, < 0.10 → C
4. No estimate if none of the above available

Useful mass fractions (y_k)
----------------------------
  C-type: water=20%, iron=16.6%, nickel=1.4%, cobalt=0.2%
          Source: Brophy et al. (2012) KISS report (Asterank uses same)
  M-type: iron=88%, nickel=10%, cobalt=0.5%
          Source: standard iron meteorite composition (Asterank/Webster 2013)
  S-type: silicate-dominated, negligible extractable fraction
          Source: Asterank (Webster 2013) — effectively zero

Bulk densities
--------------
  C: 1330 kg/m^3, S: 2720 kg/m^3, M: 4500 kg/m^3
  Source: Carry (2012), Table 3, r_20 column

Material prices ($/kg)
-----------------------
  Water: $0.01/kg, Iron: $2e-7/kg, Nickel: $0.00002/kg, Cobalt: $0.20/kg
  Source: Asterank (Webster 2013) — current market prices
"""

import numpy as np
import pandas as pd

# Bulk densities (kg/m^3) — Carry (2012), Table 3, r_20 column
RHO = {
    'C': 1330.0,   # C-type: 1.33 g/cm³
    'S': 2720.0,   # S-type: 2.72 g/cm³
    'M': 4500.0,   # X-complex metallic (Xc/Xk): ~4.2-4.9 g/cm³, midpoint used
}
RHO_DEFAULT = 2000.0

# Material composition fractions (fraction of bulk mass) by class
# C-type: Brophy et al. (2012) KISS report
# M-type: standard iron meteorite composition (Webster/Asterank 2013)
# S-type: silicate-dominated, negligible resource value (Webster/Asterank 2013)

COMPOSITION = {
    'C': {'water': 0.200, 'iron': 0.166, 'nickel': 0.014, 'cobalt': 0.002},
    'M': {'water': 0.000, 'iron': 0.880, 'nickel': 0.100, 'cobalt': 0.005},
    'S': {'water': 0.000, 'iron': 0.000, 'nickel': 0.000, 'cobalt': 0.000},
}

# Total useful mass fraction y_k (sum of extractable materials)
Y = {
    'C': sum(COMPOSITION['C'].values()),  # ~0.382
    'M': sum(COMPOSITION['M'].values()),  # ~0.985
    'S': 0.0,
}

# Material prices ($/kg) — Webster/Asterank (2013)
PRICE_PER_KG = {
    'water':  0.01,
    'iron':   2e-7,
    'nickel': 0.00002,
    'cobalt': 0.20,
}

def value_per_kg(comp_class):
    """Return $/kg of useful material for a given composition class."""
    total = 0.0
    for mat, frac in COMPOSITION[comp_class].items():
        total += PRICE_PER_KG.get(mat, 0.0) * frac
    return total

# Deterministic class assignment

# Bus-DeMeo (spec_B) → resource class
# Source: DeMeo et al. (2009)
SPEC_B_CLASS = {
    # C-complex → C
    'C': 'C', 'Cb': 'C', 'Cg': 'C', 'Cgh': 'C', 'Ch': 'C', 'B': 'C',
    # S-complex → S
    'S': 'S', 'Sq': 'S', 'Sr': 'S', 'Sw': 'S', 'Sa': 'S',
    'Q': 'S', 'V': 'S', 'A': 'S', 'R': 'S', 'K': 'S', 'L': 'S',
    # X-complex → resolved by albedo (Tholen 1984, Clark et al. 2004)
    'X': 'X', 'Xc': 'X', 'Xe': 'X', 'Xk': 'X',
    # D-type → treat as C (primitive, outer belt)
    'D': 'C',
    # T-type → ambiguous, treat as C (dark, primitive-like)
    'T': 'C',
}

# Tholen (spec_T) → resource class
# Source: Tholen (1984) — M, E, P directly defined by albedo in this taxonomy
SPEC_T_CLASS = {
    'C': 'C', 'B': 'C', 'F': 'C', 'G': 'C', 'P': 'C', 'D': 'C',
    'S': 'S', 'Q': 'S', 'V': 'S', 'A': 'S', 'R': 'S',
    'M': 'M',   # directly metallic in Tholen
    'E': 'S',   # enstatite achondrite — iron-poor silicate, treat as S
    'X': 'X',   # ambiguous — resolve by albedo
    'T': 'C',
}


def xcomplex_from_albedo(albedo):
    """
    Resolve X-complex into E/M/P using albedo thresholds.
    Source: Tholen (1984), confirmed by Clark et al. (2004).
    Note: Clark et al. (2004) warns albedo alone is imperfect —
    ~50% of M-types show silicate contamination. This residual
    ambiguity is captured in sigma_M.
    Returns resource class: 'C' (P-type), 'M', or 'S' (E-type).
    """
    if pd.isna(albedo):
        return None  # cannot classify — exclude
    elif albedo > 0.30:
        return 'S'   # E-type: enstatite, iron-poor silicate
    elif albedo >= 0.10:
        return 'M'   # M-type: metallic
    else:
        return 'C'   # P-type: primitive carbonaceous


def get_composition_class(row):
    """
    Return (resource_class, method) where method describes how class was inferred.
    Returns (None, 'no_data') if classification is not possible.
    """
    sb = str(row.get('spec_B', '')).strip() if pd.notna(row.get('spec_B')) else ''
    st = str(row.get('spec_T', '')).strip() if pd.notna(row.get('spec_T')) else ''
    albedo = row.get('albedo', np.nan)
    try:
        albedo = float(albedo)
    except (ValueError, TypeError):
        albedo = np.nan

    # 1. spec_B
    if sb in SPEC_B_CLASS:
        cls = SPEC_B_CLASS[sb]
        if cls == 'X':
            resolved = xcomplex_from_albedo(albedo)
            if resolved is None:
                return None, 'xcomplex_no_albedo'
            return resolved, 'spec_B+albedo'
        return cls, 'spec_B'

    # 2. spec_T
    if st in SPEC_T_CLASS:
        cls = SPEC_T_CLASS[st]
        if cls == 'X':
            resolved = xcomplex_from_albedo(albedo)
            if resolved is None:
                return None, 'xcomplex_no_albedo'
            return resolved, 'spec_T+albedo'
        return cls, 'spec_T'

    # 3. albedo alone — Tholen (1984) thresholds
    if not pd.isna(albedo):
        if albedo > 0.30:
            return 'S', 'albedo_only'
        elif albedo >= 0.10:
            return 'M', 'albedo_only'
        else:
            return 'C', 'albedo_only'

    return None, 'no_data'


# Mass estimation

def estimate_mass(row, rho):
    """
    Estimate bulk mass (kg) from diameter or H magnitude.
    Diameter formula: D(km) = 1329 / sqrt(pv) * 10^(-H/5)
    Source: Fowler & Chillemi (1992), standard JPL formula.
    """
    try:
        diam_km = float(row.get('diameter', np.nan))
    except (ValueError, TypeError):
        diam_km = np.nan

    if pd.isna(diam_km):
        try:
            H = float(row.get('H', np.nan))
        except (ValueError, TypeError):
            return np.nan
        try:
            pv = float(row.get('albedo', np.nan))
        except (ValueError, TypeError):
            pv = np.nan
        if pd.isna(H):
            return np.nan
        pv = pv if not pd.isna(pv) else 0.15  # assumed albedo fallback
        diam_km = 1329.0 / np.sqrt(pv) * 10 ** (-H / 5.0)

    r_m = (diam_km * 1e3) / 2.0
    volume = (4.0 / 3.0) * np.pi * r_m ** 3
    return rho * volume


# Per-row computation

def compute_row(row):
    comp_class, method = get_composition_class(row)

    if comp_class is None:
        return None, method, np.nan, np.nan, np.nan

    rho = RHO.get(comp_class, RHO_DEFAULT)
    m_bulk = estimate_mass(row, rho)

    if pd.isna(m_bulk):
        return comp_class, method, np.nan, np.nan, np.nan

    y = Y[comp_class]
    E_M = m_bulk * y

    # sigma_M: uncertainty from Clark et al. (2004) M-type caveat —
    # assume ±30% uncertainty on useful mass fraction for M-type,
    # ±10% for C and S (well-characterised from KISS / Asterank)
    sigma_frac = {'C': 0.10, 'S': 0.10, 'M': 0.30}
    sigma_M = E_M * sigma_frac[comp_class]

    # Dollar value: E[M_useful] split by material fractions × price
    value_usd = m_bulk * value_per_kg(comp_class)

    return comp_class, method, E_M, sigma_M, value_usd


# Main
if __name__ == '__main__':
    print("Loading dataset_cleaned.csv ...")
    df = pd.read_csv('dataset_cleaned.csv', low_memory=False)
    print(f"  {len(df):,} asteroids loaded")

    records = df.apply(compute_row, axis=1, result_type='expand')
    records.columns = ['comp_class', 'class_method', 'E_M_useful_kg', 'sigma_M_kg', 'value_usd']

    df_out = pd.concat([
        df[['full_name', 'class', 'neo', 'a', 'e', 'i',
            'diameter', 'H', 'albedo', 'spec_B', 'spec_T', 'moid']],
        records
    ], axis=1)

    output_path = 'asteroid_values.csv'
    df_out.to_csv(output_path, index=False)
    print(f"\nWrote {output_path}")
    print(f"  Final shape: {df_out.shape[0]:,} rows x {df_out.shape[1]} columns")

    classified = df_out['comp_class'].notna().sum()
    print(f"\n--- Classification coverage ---")
    print(f"  Classified          : {classified:,} ({100*classified/len(df_out):.1f}%)")
    print(f"\n  Method breakdown:")
    print(df_out['class_method'].value_counts().to_string())
    print(f"\n  Class breakdown (classified only):")
    print(df_out['comp_class'].value_counts().to_string())

    print(f"\n--- Value coverage ---")
    valued = df_out['value_usd'].notna().sum()
    print(f"  Asteroids with value estimate: {valued:,} ({100*valued/len(df_out):.1f}%)")

    print("\n--- Top 10 NEAs by E[M_useful] ---")
    nea = df_out[df_out['neo'] == 'Y'].dropna(subset=['E_M_useful_kg'])
    top = nea.nlargest(10, 'E_M_useful_kg')[
        ['full_name', 'comp_class', 'class_method', 'albedo',
         'E_M_useful_kg', 'sigma_M_kg', 'value_usd']
    ]
    pd.set_option('display.float_format', '{:.3e}'.format)
    print(top.to_string(index=False))

    print("\n--- Top 10 NEAs by value ($USD) ---")
    top_val = nea.nlargest(10, 'value_usd')[
        ['full_name', 'comp_class', 'class_method', 'albedo',
         'E_M_useful_kg', 'sigma_M_kg', 'value_usd']
    ]
    print(top_val.to_string(index=False))

    print("\nDone.")