# -*- coding: utf-8 -*-
"""continuous_optimizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bD9U7b9n6WMFcwh1qJRl2x8dobG3aNue
"""

"""
continuous_optimizer_v2.py

Full continuous optimization:
    max_{x} S_hat(x) * p(x)

where:
    S_hat(x) = GP surrogate prediction of direct_minus_mining_usd ($)
               POSITIVE = mining cheaper than direct launch
               Source: gp_economics.pkl trained on Ishaan's training data
    p(x)     = probability a real NEA exists near x = [a, e, i]
               Source: existence_model.py

No lambda here — the economic objective already captures the full
cost/value tradeoff. Lambda sensitivity is shown separately via the
composition model sensitivity analysis already completed.

For the continuous optimization we additionally sweep a risk-aversion
parameter lambda_econ that penalises GP uncertainty:

    max_{x} (S_hat(x) - lambda_econ * sigma_S(x)) * p(x)

This is the economics analogue of the mass-based sensitivity analysis.
"""

import numpy as np
import pandas as pd
import pickle
import matplotlib.pyplot as plt
from scipy.optimize import minimize
from scipy.spatial.distance import cdist

# Load GP economics surrogate
with open('gp_economics.pkl', 'rb') as f:
    bundle = pickle.load(f)

gp       = bundle['gp']
scaler_X = bundle['scaler_X']
scaler_y = bundle['scaler_y']
DV_MAX   = bundle['dv_max']
print(f"Loaded GP economics surrogate")
print(f"  R²_train={bundle['r2_train']:.3f}  R²_test={bundle['r2_test']:.3f}")
print(f"  Target: direct_minus_mining_usd ($)")

# Load p(x) existence model
C_exist = np.load('existence_centers.npy')
S_exist = np.load('existence_sigmas.npy')
p_max   = float(np.load('existence_pmax.npy')[0])

def p_existence(x_aei):
    x    = np.array(x_aei, dtype=float)
    diff = (x - C_exist) / S_exist
    r2   = np.sum(diff**2, axis=1)
    return float(np.sum(np.exp(-0.5 * r2))) / p_max

# GP prediction
def predict_savings(a, e, i, w_deg):
    """
    Predict direct_minus_mining_usd and uncertainty.
    Returns (savings_$, sigma_$).
    Positive savings = mining is cheaper than direct launch.
    """
    w_r = np.deg2rad(w_deg)
    x_s = scaler_X.transform([[a, e, i, np.sin(w_r), np.cos(w_r)]])
    s_s, sig_s = gp.predict(x_s, return_std=True)
    s   = float(scaler_y.inverse_transform(s_s.reshape(-1,1))[0,0])
    sig = float(sig_s[0]) * scaler_y.scale_[0]
    return s, sig

# Combined objective: (S_hat - lambda * sigma_S) * p(x)

def combined_objective(x, lam):
    """
    Returns -(S_hat(x) - lam*sigma_S(x)) * p(x) for minimization.
    x = [a, e, i, w_deg]
    lam = risk-aversion on GP uncertainty (0 = pure expected savings)
    """
    a, e, i, w = x

    # Soft bounds
    penalty = 0.0
    if not (0.5 <= a <= 4.2): penalty += 1e12*(min(a-0.5,0)**2 + max(a-4.2,0)**2)
    if not (0.0 <= e <= 0.9): penalty += 1e12*(min(e,0)**2     + max(e-0.9,0)**2)
    if not (0.0 <= i <= 35.): penalty += 1e12*(min(i,0)**2     + max(i-35.,0)**2)
    if penalty > 0:
        return penalty

    s, sig = predict_savings(a, e, i, w)
    p_val  = p_existence([a, e, i])

    return -((s - lam * sig) * p_val)

# Load catalog and merge w
print("\nLoading catalog...")
df_vals    = pd.read_csv('asteroid_values.csv',  low_memory=False)
df_cleaned = pd.read_csv('dataset_cleaned.csv',   low_memory=False)

df_vals = df_vals.merge(
    df_cleaned[['full_name','w','om']].drop_duplicates('full_name'),
    on='full_name', how='left'
)

nea = df_vals[
    (df_vals['neo'] == 'Y') &
    df_vals['comp_class'].notna() &
    df_vals['w'].notna() &
    df_vals['E_M_useful_kg'].notna()
].copy()
print(f"  {len(nea):,} NEAs with full data")

# L-BFGS-B optimization for lambda_econ values
LAMBDAS    = [0.0, 0.5, 1.0, 2.0]
BOUNDS     = [(0.5, 4.2), (0.0, 0.9), (0.0, 35.0), (0.0, 360.0)]
N_RESTARTS = 20
np.random.seed(42)

print(f"\nRunning L-BFGS-B: {len(LAMBDAS)} λ values × {N_RESTARTS} restarts each...")
print(f"  Objective: max (S_hat - λ·σ_S) · p(x)\n")

opt_results = {}

for lam in LAMBDAS:
    best_val = np.inf
    best_x   = None

    for _ in range(N_RESTARTS):
        x0 = np.array([
            np.random.uniform(0.5, 3.5),
            np.random.uniform(0.0, 0.5),
            np.random.uniform(0.0, 30.0),
            np.random.uniform(0.0, 360.0),
        ])
        res = minimize(combined_objective, x0, args=(lam,),
                       method='L-BFGS-B', bounds=BOUNDS,
                       options={'maxiter': 500, 'ftol': 1e-10})
        if res.fun < best_val:
            best_val = res.fun
            best_x   = res.x

    opt_results[lam] = best_x
    a, e, i, w = best_x
    s, sig     = predict_savings(a, e, i, w)
    p_val      = p_existence([a, e, i])
    obj        = (s - lam*sig) * p_val

    print(f"  λ={lam:.1f} │ x*: a={a:.3f} e={e:.3f} i={i:.1f}° w={w:.1f}° │ "
          f"S_hat=${s/1e6:.0f}M  σ=${sig/1e6:.0f}M  "
          f"p={p_val:.3f}  obj=${obj/1e6:.0f}M")

# Find 10 nearest catalog NEAs to each x*
print("\n--- Nearest catalog NEAs to x* ---\n")

nea_w_r     = np.deg2rad(nea['w'].values)
X_catalog   = np.column_stack([nea['a'], nea['e'], nea['i'],
                                np.sin(nea_w_r), np.cos(nea_w_r)])
X_catalog_s = scaler_X.transform(X_catalog)

all_candidates = {}

for lam in LAMBDAS:
    x_star     = opt_results[lam]
    a, e, i, w = x_star
    w_r        = np.deg2rad(w)
    x_star_s   = scaler_X.transform([[a, e, i, np.sin(w_r), np.cos(w_r)]])

    dists           = cdist(x_star_s, X_catalog_s).ravel()
    nea_copy        = nea.copy()
    nea_copy['dist'] = dists

    candidates = (nea_copy[nea_copy['comp_class'].isin(['C', 'M'])]
                  .nsmallest(10, 'dist')
                  [['full_name','comp_class','a','e','i','w',
                    'E_M_useful_kg','sigma_M_kg','albedo',
                    'spec_B','spec_T','dist']])
    all_candidates[lam] = candidates

    print(f"λ={lam:.1f} — 10 nearest NEAs to x* "
          f"[a={a:.2f} e={e:.3f} i={i:.1f}° w={w:.1f}°]:")
    print(f"  {'Name':35s} {'cls':>4} {'a':>5} {'e':>5} {'i':>5}  "
          f"{'S_hat ($M)':>10}  {'p(x)':>6}")
    for _, r in candidates.iterrows():
        s_r, _ = predict_savings(r['a'], r['e'], r['i'], r['w'])
        p_r    = p_existence([r['a'], r['e'], r['i']])
        print(f"  {r['full_name'][:35]:35s} {r['comp_class']:>4} "
              f"{r['a']:5.2f} {r['e']:5.3f} {r['i']:5.1f}°  "
              f"{s_r/1e6:>10.1f}  {p_r:>6.3f}")
    print()

# Plot: x* movement + p(x) background + savings contours
fig, axes = plt.subplots(1, 2, figsize=(14, 6))
colors = plt.cm.plasma(np.linspace(0.1, 0.9, len(LAMBDAS)))

# p(x) background grid
a_grid = np.linspace(0.5, 4.2, 60)
e_grid = np.linspace(0.0, 0.9, 60)
AA, EE = np.meshgrid(a_grid, e_grid)
PP     = np.array([[p_existence([a_, e_, 10.0]) for a_ in a_grid]
                    for e_ in e_grid])

# GP savings on same grid (at median i and w)
SS = np.array([[predict_savings(a_, e_, 10.0, 90.0)[0]
                for a_ in a_grid] for e_ in e_grid])

ax = axes[0]
cf = ax.contourf(AA, EE, PP, levels=20, cmap='Blues', alpha=0.5)
plt.colorbar(cf, ax=ax, label='p(x)')
sub = nea.copy()
ax.scatter(sub['a'], sub['e'], alpha=0.1, s=5, color='grey')
for j, lam in enumerate(LAMBDAS):
    xs = opt_results[lam]
    ax.scatter(xs[0], xs[1], s=150, color=colors[j], zorder=6,
               edgecolors='black', lw=0.8, label=f'λ={lam}')
    ax.annotate(f'λ={lam}', (xs[0]+0.03, xs[1]+0.01),
                fontsize=8, color=colors[j])
for j in range(len(LAMBDAS)-1):
    x1 = opt_results[LAMBDAS[j]]; x2 = opt_results[LAMBDAS[j+1]]
    ax.annotate('', xy=(x2[0],x2[1]), xytext=(x1[0],x1[1]),
                arrowprops=dict(arrowstyle='->', color='red', lw=1.5))
ax.set_xlabel('a (AU)'); ax.set_ylabel('e')
ax.set_title('x* = argmax (S_hat − λσ)·p(x)\nBackground: p(x) existence probability')
ax.legend(fontsize=8); ax.grid(True, alpha=0.2)

ax = axes[1]
# Savings contours
levels_s = np.linspace(np.percentile(SS, 5), np.percentile(SS, 95), 20)
cf2 = ax.contourf(AA, EE, SS/1e6, levels=levels_s/1e6,
                   cmap='RdYlGn', alpha=0.6)
plt.colorbar(cf2, ax=ax, label='Predicted savings ($M)\n+ve = mining cheaper')
ax.contour(AA, EE, SS/1e6, levels=[0], colors='black',
           linewidths=1.5, linestyles='--')
ax.scatter(sub['a'], sub['e'], alpha=0.1, s=5, color='grey')
for j, lam in enumerate(LAMBDAS):
    xs = opt_results[lam]
    ax.scatter(xs[0], xs[1], s=150, color=colors[j], zorder=6,
               edgecolors='black', lw=0.8, label=f'λ={lam}')
ax.set_xlabel('a (AU)'); ax.set_ylabel('e')
ax.set_title('x* overlaid on GP savings landscape\n'
             'Dashed line: breakeven (savings = $0)')
ax.legend(fontsize=8); ax.grid(True, alpha=0.2)

plt.tight_layout()
plt.savefig('continuous_optimization_economics.png', dpi=150, bbox_inches='tight')
plt.show()
print("Saved → continuous_optimization_economics.png")

# Save candidates
rows = []
for lam, df_c in all_candidates.items():
    dc = df_c.copy()
    dc['lambda_econ'] = lam
    rows.append(dc)

pd.concat(rows, ignore_index=True).to_csv('mission_candidates_economics.csv',
                                           index=False)
print("Saved → mission_candidates_economics.csv")
print("\nDone.")

import pandas as pd
import numpy as np
import pickle

df_train = pd.read_csv('training_set_1000_ntp.csv')

# Load your GP
with open('gp_economics.pkl', 'rb') as f:
    b = pickle.load(f)
gp, sx, sy = b['gp'], b['scaler_X'], b['scaler_y']

def gp_predict(a, e, i, w):
    w_r = np.deg2rad(w)
    xs = sx.transform([[a, e, i, np.sin(w_r), np.cos(w_r)]])
    s = sy.inverse_transform(gp.predict(xs).reshape(-1,1))[0,0]
    return s

# GP vs actual for ALL 32 profitable training points
print("GP prediction vs ground truth — 32 profitable asteroids:")
print(f"{'Name':30s} {'Actual':>10} {'GP pred':>10} {'error':>10}")
profitable = df_train[df_train['direct_minus_mining_usd']>0].copy()
for _, r in profitable.iterrows():
    pred = gp_predict(r['a'], r['e'], r['i'], r['w'])
    actual = r['direct_minus_mining_usd']
    print(f"  {str(r['full_name']).strip():30s} "
          f"{actual/1e6:>8.1f}M  {pred/1e6:>8.1f}M  "
          f"{(pred-actual)/1e6:>+8.1f}M")