# -*- coding: utf-8 -*-
"""Surrogate_Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ETaiWOt1n1ZKx2IctJZ3_u1DN9IXEdb2
"""

"""
sensitivity_plot.py

Visualises sensitivity analysis results:
1. Score vs lambda for top candidates (C and M types)
2. Crossover plot showing where C-types become preferred over M-types
3. Top 10 ranking table at each lambda
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle

import importlib.util, sys


# C-type representative: 308635 (2005 YU55) — dv=1.87, E_M=191,000
# M-type representative: 469445 (2002 LT24) — dv=2.14, E_M=492,500

lambdas = np.linspace(0, 3.0, 100)

# C-type score vs lambda
E_M_C    = 191_000.0   # kg  (500,000 * 0.382)
sigma_C  = 19_100.0    # kg  (10% of E_M)
C_hat_C  = 6_224.0     # kg  propellant (dv=1.87 km/s)

# M-type score vs lambda
E_M_M    = 492_500.0   # kg  (500,000 * 0.985)
sigma_M  = 147_750.0   # kg  (30% of E_M)
C_hat_M  = 6_929.0     # kg  propellant (dv=2.14 km/s)

score_C = E_M_C  - lambdas * sigma_C  - C_hat_C
score_M = E_M_M  - lambdas * sigma_M  - C_hat_M

# Crossover point
crossover_lam = (E_M_M - C_hat_M - E_M_C + C_hat_C) / (sigma_M - sigma_C)

fig, axes = plt.subplots(1, 2, figsize=(13, 5))

# Score vs lambda
ax = axes[0]
ax.plot(lambdas, score_C / 1e3, 'b-',  lw=2.5,
        label='C-type (2005 YU55)\nΔv=1.87 km/s, σ=10%')
ax.plot(lambdas, score_M / 1e3, 'r--', lw=2.5,
        label='M-type (2002 LT24)\nΔv=2.14 km/s, σ=30%')
ax.axhline(0, color='k', lw=0.8, ls=':')

if 0 < crossover_lam < 3:
    cross_score = (E_M_C - lambdas[0]*sigma_C - C_hat_C +
                   E_M_M - lambdas[0]*sigma_M - C_hat_M) / 2
    ax.axvline(crossover_lam, color='green', lw=1.5, ls='--',
               label=f'Crossover λ={crossover_lam:.2f}')
    ax.annotate(f'λ={crossover_lam:.2f}\nC preferred above',
                xy=(crossover_lam, np.interp(crossover_lam, lambdas, score_C)/1e3),
                xytext=(crossover_lam+0.2,
                        np.interp(crossover_lam, lambdas, score_C)/1e3 + 30),
                arrowprops=dict(arrowstyle='->', color='green'),
                fontsize=9, color='green')

ax.set_xlabel('Risk-aversion parameter λ', fontsize=12)
ax.set_ylabel('Objective score f(x) (×10³ kg)', fontsize=12)
ax.set_title('Sensitivity Analysis: Score vs λ\nfor representative C-type and M-type NEAs')
ax.legend(fontsize=9)
ax.grid(True, alpha=0.3)

#  Score drop relative to lambda=0
ax = axes[1]
ax.plot(lambdas, (score_C - score_C[0]) / 1e3, 'b-',  lw=2.5,
        label='C-type (σ=10%)')
ax.plot(lambdas, (score_M - score_M[0]) / 1e3, 'r--', lw=2.5,
        label='M-type (σ=30%)')
ax.axhline(0, color='k', lw=0.8)
ax.set_xlabel('Risk-aversion parameter λ', fontsize=12)
ax.set_ylabel('Score change from λ=0 (×10³ kg)', fontsize=12)
ax.set_title('Score Penalty from Composition Uncertainty\n(steeper = more sensitive to risk aversion)')
ax.legend(fontsize=10)
ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('sensitivity_analysis.png', dpi=150, bbox_inches='tight')
plt.show()
print(f"Saved → sensitivity_analysis.png")
print(f"\nCrossover λ = {crossover_lam:.3f}")
print(f"For λ > {crossover_lam:.2f}: C-type (2005 YU55) scores higher than M-type (2002 LT24)")
print(f"At λ=0:   M-type advantage = {(score_M[0]-score_C[0])/1e3:.1f}×10³ kg")
print(f"At λ=1:   M-type advantage = {(score_M[50]-score_C[50])/1e3:.1f}×10³ kg")
idx = np.argmin(np.abs(lambdas - 2.0))
print(f"At λ=2:   M-type advantage = {(score_M[idx]-score_C[idx])/1e3:.1f}×10³ kg")

# Summary table
print(f"\n--- Summary table for report ---")
print(f"{'λ':>6}  {'C-type score (kg)':>18}  {'M-type score (kg)':>18}  {'Preferred':>10}")
for lam in [0.0, 0.25, 0.5, 1.0, 2.0]:
    sc = E_M_C - lam*sigma_C - C_hat_C
    sm = E_M_M - lam*sigma_M - C_hat_M
    pref = 'C-type' if sc > sm else 'M-type'
    print(f"{lam:>6.2f}  {sc:>18,.0f}  {sm:>18,.0f}  {pref:>10}")

print("\nDone.")

"""
surrogate_training.py

Fits ONE GP surrogate:
  (a, e, i, sin_w, cos_w) → direct_minus_mining_usd

  direct_minus_mining_usd = direct_launch_cost - mining_mission_cost
  POSITIVE = asteroid mining saves money vs launching same cargo from Earth
  NEGATIVE = direct launch is cheaper

Train/test split: 800 train, ~199 test
R² reported on both sets to check for overfitting.

Features: (a, e, i, sin_w, cos_w) — 5D
  Omega dropped: shown to have no predictive value in test
  w (argument of perihelion) encoded as sin/cos for angular periodicity
"""

import numpy as np
import pandas as pd
import pickle
import matplotlib.pyplot as plt
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel, WhiteKernel
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

CSV_PATH = 'training_set_1000_ntp.csv'
SAVE_DIR = ''

# Load
print("Loading training set...")
df = pd.read_csv(CSV_PATH)
print(f"  {len(df)} rows loaded")

# Check target distribution
target_col = 'direct_minus_mining_usd'
print(f"\n  Target: {target_col}")
print(f"  Mean  : ${df[target_col].mean():>15,.0f}")
print(f"  Std   : ${df[target_col].std():>15,.0f}")
print(f"  Min   : ${df[target_col].min():>15,.0f}")
print(f"  Max   : ${df[target_col].max():>15,.0f}")
print(f"  Positive (mining saves money): "
      f"{(df[target_col] > 0).sum()} / {len(df)} "
      f"({100*(df[target_col]>0).mean():.1f}%)")

# Features
w_r = np.deg2rad(df['w'].values)
X   = np.column_stack([
    df['a'].values,
    df['e'].values,
    df['i'].values,
    np.sin(w_r),
    np.cos(w_r),
])
y   = df[target_col].values

print(f"\n  Features: (a, e, i, sin_w, cos_w) — 5D")
print(f"  a: [{X[:,0].min():.2f}, {X[:,0].max():.2f}] AU")
print(f"  e: [{X[:,1].min():.3f}, {X[:,1].max():.3f}]")
print(f"  i: [{X[:,2].min():.2f}, {X[:,2].max():.2f}] deg")

# Feasibility constraint — max dv for 10-year window
TIME_LIMIT = 10.0
dv_max = df[df['total_time_years'] <= TIME_LIMIT]['dv_out_kms'].max()
print(f"\n  Δv constraint (≤{TIME_LIMIT} yr): {dv_max:.3f} km/s")

# 800 train / 199 test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, train_size=800, random_state=42)
print(f"\n  Train: {len(X_train)}, Test: {len(X_test)}")

scaler_X  = StandardScaler()
X_train_s = scaler_X.fit_transform(X_train)
X_test_s  = scaler_X.transform(X_test)

scaler_y  = StandardScaler()
y_train_s = scaler_y.fit_transform(y_train.reshape(-1,1)).ravel()

# GP
kernel = (
    ConstantKernel(1.0, (1e-3, 1e3)) *
    RBF(length_scale=[1.0]*5,
        length_scale_bounds=[(1e-2, 50.0)]*5) +
    WhiteKernel(noise_level=1e-2, noise_level_bounds=(1e-5, 1.0))
)
gp = GaussianProcessRegressor(
    kernel=kernel,
    n_restarts_optimizer=15,
    normalize_y=False,
    alpha=1e-6
)

print("\nFitting GP surrogate...")
gp.fit(X_train_s, y_train_s)

try:
    ls    = gp.kernel_.k1.k2.length_scale
    names = ['a', 'e', 'i', 'sin_w', 'cos_w']
    print(f"\n  Fitted length scales (larger = less sensitive):")
    for n, l in zip(names, ls):
        bar = '█' * int(min(l*2, 30))
        print(f"    {n:8s}: {l:6.3f}  {bar}")
except:
    print(f"  Kernel: {gp.kernel_}")

# Evaluate on train and test
y_tr_pred_s = gp.predict(X_train_s, return_std=False)
y_tr_pred   = scaler_y.inverse_transform(y_tr_pred_s.reshape(-1,1)).ravel()

y_te_pred_s, sigma_s = gp.predict(X_test_s, return_std=True)
y_te_pred = scaler_y.inverse_transform(y_te_pred_s.reshape(-1,1)).ravel()
sigma     = sigma_s * scaler_y.scale_[0]

r2_train   = r2_score(y_train, y_tr_pred)
rmse_train = np.sqrt(mean_squared_error(y_train, y_tr_pred))

r2_test    = r2_score(y_test, y_te_pred)
rmse_test  = np.sqrt(mean_squared_error(y_test, y_te_pred))
mae_test   = np.abs(y_test - y_te_pred).mean()

print(f"\n{'':=<55}")
print(f"  {'':20s} {'Train (n=800)':>15}  {'Test (n=199)':>15}")
print(f"  {'':=<54}")
print(f"  {'R²':20s} {r2_train:>15.4f}  {r2_test:>15.4f}")
print(f"  {'RMSE ($)':20s} {rmse_train:>15,.0f}  {rmse_test:>15,.0f}")
print(f"  {'MAE ($)':20s} {'':>15}  {mae_test:>15,.0f}")
print(f"{'':=<55}")

gap = r2_train - r2_test
if gap > 0.15:
    print("  ⚠  Large gap → overfitting")
elif gap > 0.05:
    print("  ✓  Small gap → mild overfitting, acceptable")
else:
    print("  ✓  Train ≈ Test → good generalisation")

# Validation plots
fig, axes = plt.subplots(1, 3, figsize=(15, 5))
residuals = y_te_pred - y_test

ax = axes[0]
ax.scatter(y_test/1e6,  y_te_pred/1e6,  alpha=0.7, s=25,
           color='steelblue', edgecolors='none',
           label=f'Test  R²={r2_test:.3f}', zorder=3)
ax.scatter(y_train/1e6, y_tr_pred/1e6, alpha=0.12, s=10,
           color='orange', edgecolors='none',
           label=f'Train R²={r2_train:.3f}')
lims = [y.min()/1e6 - 50, y.max()/1e6 + 50]
ax.plot(lims, lims, 'r--', lw=1.5)
ax.axhline(0, color='k', lw=0.8, ls=':')
ax.axvline(0, color='k', lw=0.8, ls=':')
ax.set_xlabel('True direct−mining savings ($M)')
ax.set_ylabel('Predicted savings ($M)')
ax.set_title(f'GP Surrogate: direct_minus_mining_usd\n'
             f'R²_train={r2_train:.3f}  R²_test={r2_test:.3f}')
ax.legend(fontsize=9); ax.set_xlim(lims); ax.set_ylim(lims)

ax = axes[1]
sc = ax.scatter(X_test[:,0], residuals/1e6, c=X_test[:,2],
                cmap='viridis', alpha=0.7, s=25, edgecolors='none')
ax.axhline(0, color='r', lw=1.5, ls='--')
plt.colorbar(sc, ax=ax, label='i (deg)')
ax.set_xlabel('a (AU)'); ax.set_ylabel('Residual ($M)')
ax.set_title(f'Residuals vs a  RMSE=${rmse_test/1e6:.1f}M')

ax = axes[2]
ax.scatter(sigma/1e6, np.abs(residuals)/1e6, alpha=0.6, s=25,
           color='green', edgecolors='none')
z = np.polyfit(sigma, np.abs(residuals), 1)
xline = np.linspace(sigma.min(), sigma.max(), 100)
ax.plot(xline/1e6, np.polyval(z, xline)/1e6, 'r--', lw=1.5)
ax.set_xlabel('GP σ ($M)'); ax.set_ylabel('|Residual| ($M)')
ax.set_title('Uncertainty Calibration')

plt.tight_layout()
plt.savefig(SAVE_DIR + 'gp_economics_validation.png', dpi=150, bbox_inches='tight')
plt.show()
print("Saved → gp_economics_validation.png")

# Save
model_bundle = {
    'gp':         gp,
    'scaler_X':   scaler_X,
    'scaler_y':   scaler_y,
    'dv_max':     dv_max,
    'target_col': target_col,
    'r2_train':   r2_train,
    'r2_test':    r2_test,
    'features':   ['a', 'e', 'i', 'sin_w', 'cos_w'],
}
with open(SAVE_DIR + 'gp_economics.pkl', 'wb') as f:
    pickle.dump(model_bundle, f)
print("Saved → gp_economics.pkl")

# Prediction function
def predict_savings(a, e, i, w_deg):
    """
    Predict direct_minus_mining_usd ($) for orbital elements (a, e, i, w).
    Positive = mining cheaper than direct launch.
    Returns (savings_mean, savings_sigma).
    """
    w_r = np.deg2rad(w_deg)
    x_s = scaler_X.transform([[a, e, i, np.sin(w_r), np.cos(w_r)]])
    s_s, sig_s = gp.predict(x_s, return_std=True)
    s   = scaler_y.inverse_transform(s_s.reshape(-1,1))[0,0]
    sig = float(sig_s[0]) * scaler_y.scale_[0]
    return s, sig

print("\n--- Sanity check ---")
for a_, e_, i_, w_, label in [
        (1.5, 0.10,  5.0,  45.0, "easy NEA"),
        (2.5, 0.25, 15.0, 180.0, "mid-belt"),
        (4.5, 0.50, 30.0, 270.0, "expensive")]:
    s, sig = predict_savings(a_, e_, i_, w_)
    verdict = "mining cheaper" if s > 0 else "direct cheaper"
    print(f"  {label:12s} → savings=${s/1e6:.1f}M ± ${sig/1e6:.1f}M  ({verdict})")

print("\nDone.")